services:
  frontend_csc_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - frontend_csc:/app/frontend

  nginx:
    image: nginx:alpine
    container_name: nginx_csc
    depends_on:
      - frontend_csc_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - frontend_csc:/usr/share/nginx/html:ro  # Serve React build files
    ports:
      - "8888:80"  # Nginx serves frontend
    restart: unless-stopped

volumes:
  frontend_csc: